INPUT = -2
OUTPUT = 9999

INPUT_NAME = str(INPUT)+'NN_INPUT'
OUTPUT_NAME = str(OUTPUT)+'NN_OUTPUT'

UNEVALUATED_FITNESS = -1

# Search phase
CHANNELS_NO = 32
# Full training phase
FULL_CHANNELS_NO = 64


DROPOUT_PROB = 0.1
